config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :promotions do
      resources :promotion_rules
    end
  end
end

app/models/calculator/free_shipping.rb
class Calculator::FreeShipping < ::Calculator

  def self.description
    I18n.t("free_shipping")
  end

  def self.register
    super
    Promotion.register_calculator(self)
  end

  def compute(object)
    if object.is_a?(Array)
      return if object.empty?
      order = object.first.order
    else
      order = object
    end

    order.ship_total
  end

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  has_many  :promotion_credits,    :as => :source
  calculated_adjustments
  alias credits promotion_credits

  has_many :promotion_rules, :autosave => true
  accepts_nested_attributes_for :promotion_rules
  alias_method :rules, :promotion_rules

  validates :name, :presence => true

  # TODO: Remove that after fix for https://rails.lighthouseapp.com/projects/8994/tickets/4329-has_many-through-association-does-not-link-models-on-association-save
  # is provided
  def save(*)
    if super
      promotion_rules.each { |p| p.save }
    end
  end

  MATCH_POLICIES = %w(all any)

  scope :automatic, where("code IS NULL OR code = ''")
  scope :manual, where("code IS NOT NULL AND code <> ''")

  def eligible?(order)
    !expired? && rules_are_eligible?(order)
  end

  # Changed the credits_count comparison to '>', because the expired check happens in the on_save when for update_attributes in OrdersController#update
  # and again in the Order#update!'s call to update_adjustments.  Problem is that the 2nd call will see the count as == usage_limit
  def expired?
    starts_at && Time.now < starts_at ||
    expires_at && Time.now > expires_at ||
    usage_limit && credits_count > usage_limit
  end

  def credits_count
    credits.with_order.count
  end

  def rules_are_eligible?(order)
    return true if rules.none?
    if match_policy == 'all'
      rules.all?{|r| r.eligible?(order)}
    else
      rules.any?{|r| r.eligible?(order)}
    end
  end

  def create_discount(order)
    return if order.promotion_credit_exists?(self)
    if eligible?(order) and amount = calculator.compute(order)
      amount = order.item_total if amount > order.item_total
      order.promotion_credits.reload.clear unless combine? and order.promotion_credits.all? { |credit| credit.source.combine? }
      order.update!
      PromotionCredit.create!({
          :label => "#{I18n.t(:coupon)} (#{code})",
          :source => self,
          :amount => -amount.abs,
          :order => order
        })
    end
  end



  # Products assigned to all product rules
  def products
    @products ||= rules.of_type("Promotion::Rules::Product").map(&:products).flatten.uniq
  end

end

app/models/promotion/rules/first_order.rb
class Promotion::Rules::FirstOrder < PromotionRule

  def eligible?(order)
    order.user && order.user.orders.complete.count == 0
  end

end

app/models/promotion/rules/item_total.rb
# A rule to limit a promotion to a specific user.
class Promotion::Rules::ItemTotal < PromotionRule

  preference :amount, :decimal, :default => 100.00
  preference :operator, :string, :default => '>'

  OPERATORS = ['gt', 'gte']

  def eligible?(order)
    order.item_total.send(preferred_operator == 'gte' ? :>= : :>, preferred_amount)
  end
end

app/models/promotion/rules/product.rb
# A rule to limit a promotion based on products in the order.
# Can require all or any of the products to be present.
# Valid products either come from assigned product group or are assingned directly to the rule.
class Promotion::Rules::Product < PromotionRule

  belongs_to :product_group
  has_and_belongs_to_many :products, :class_name => '::Product', :join_table => 'products_promotion_rules', :foreign_key => 'promotion_rule_id'

  MATCH_POLICIES = %w(any all)
  preference :match_policy, :string, :default => MATCH_POLICIES.first

  # scope/association that is used to test eligibility
  def eligible_products
    product_group ? product_group.products : products
  end

  def eligible?(order)
    return true if eligible_products.empty?
    if preferred_match_policy == 'all'
      eligible_products.all? {|p| order.products.include?(p) }
    else
      order.products.any? {|p| eligible_products.include?(p) }
    end
  end


  def products_source=(source)
    if source.to_s == 'manual'
      self.product_group_id = nil
    end
  end

  def product_ids_string
    product_ids.join(',')
  end
  def product_ids_string=(s)
    self.product_ids = s.to_s.split(',').map(&:strip)
  end

end

app/models/promotion/rules/sponsor.rb
class Promotion::Rules::Sponsor < PromotionRule
  belongs_to :contact

  def eligible?(order)
    true
  end
end

app/models/promotion/rules/user.rb
class Promotion::Rules::User < PromotionRule
  belongs_to :user
  has_and_belongs_to_many :users, :class_name => '::User', :join_table => 'promotion_rules_users', :foreign_key => 'promotion_rule_id'

  def eligible?(order)
    users.none? or users.include?(order.user)
  end

  def user_ids_string
    user_ids.join(',')
  end

  def user_ids_string=(s)
    self.user_ids = s.to_s.split(',').map(&:strip)
  end

end

app/models/promotion_credit.rb
class PromotionCredit < ::Adjustment
  scope :with_order, :conditions => "order_id IS NOT NULL"

  alias :adjustment_source :source

  def calculate_adjustment
    adjustment_source && calculate_coupon_credit
  end

  # Checks if credit is still applicable to order
  # If source of adjustment is credit, it checks if it's still valid
  def applicable?
    adjustment_source && adjustment_source.eligible?(order) && super
  end

  # Calculates credit for the coupon.
  #
  # If coupon amount exceeds the order item_total, credit is adjusted.
  #
  # Always returns negative non positive.
  def calculate_coupon_credit
    return 0 if order.line_items.empty?
    amount = adjustment_source.calculator.compute(order.line_items).abs
    amount = order.item_total if amount > order.item_total
    -1 * amount
  end

  def total
    map(&:amount).sum
  end
end

app/models/promotion_rule.rb
# Base class for all promotion rules
class PromotionRule < ActiveRecord::Base

  belongs_to :promotion

  scope :of_type, lambda {|t| {:conditions => {:type => t}}}

  def eligible?(order)
    raise 'eligible? should be implemented in a sub-class of Promotion::PromotionRule'
  end

  @rule_classes = nil
  @@rule_classes = Set.new
  def self.register
    @@rule_classes.add(self)
  end

  def self.rule_classes
    @@rule_classes.to_a
  end

  def self.rule_class_names
    PromotionRule.rule_classes.map(&:name)
  end

end

app/controllers/admin/promotion_rules_controller.rb
class Admin::PromotionRulesController < Admin::BaseController
  resource_controller
  belongs_to :promotion

  create.response do |wants|
    wants.html { redirect_to edit_admin_promotion_path(parent_object) }
    wants.js { render :action => 'create', :layout => false}
  end
  destroy.response do |wants|
    wants.html { redirect_to edit_admin_promotion_path(parent_object) }
    wants.js { render :action => 'destroy', :layout => false}
  end

  private

    def build_object
      return @object if @object.present?
  		if params[:promotion_rule] && params[:promotion_rule][:type]
  			@object = params[:promotion_rule][:type].constantize.new(object_params)
  			@object.promotion = parent_object
  		else
  			@object = end_of_association_chain.build(object_params)
  		end
  		@object
    end

end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < Admin::BaseController
  resource_controller
  before_filter :load_data

  update.wants.html { redirect_to edit_object_url }
  create.wants.html { redirect_to edit_object_url }
  destroy.success.wants.js { render_js_for_destroy }

  private
  def build_object
    @object ||= end_of_association_chain.send parent? ? :build : :new, object_params
    @object.calculator = params[:promotion][:calculator_type].constantize.new if params[:promotion]
  end

  def load_data
    @calculators = Promotion.calculators
  end
end

app/views/admin/promotion_rules/create.js.erb
jQuery('#rules').append('<%= escape_javascript( render(:partial => 'admin/promotions/promotion_rule', :object => object) ) %>');
jQuery('#<%= dom_id object %>').hide();
jQuery('#<%= dom_id object %>').fadeIn();
initProductRuleSourceField();
jQuery('#<%= dom_id object %> .tokeninput.products').productPicker();
jQuery('#<%= dom_id object %> .tokeninput.users').userPicker();

app/views/admin/promotion_rules/destroy.js.erb
jQuery('#<%= dom_id object %>').fadeOut().remove();

app/views/admin/promotions/_form.html.erb
<%= render "shared/error_messages", :target => @promotion %>
<fieldset id="general_fields">
  <legend><%= t(:general) %></legend>
  <%= f.field_container :name do %>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  <% end %>

  <%= f.field_container :description do %>
    <%= f.label :description %><br />
    <%= f.text_area :description, :style => "height:50px" %>
  <% end %>

  <%= f.field_container :code do %>
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  <% end %>

  <%= f.field_container :combine do %>
    <label>
      <%= f.check_box :combine %> 
      <%= t(:may_be_combined_with_other_promotions) %>
    </label>
  <% end %>

</fieldset>

<fieldset id="expiry_fields">
  <legend><%= t(:expiry) %></legend>
  <p>
    <%= f.label :usage_limit %><br />
    <%= f.text_field :usage_limit %>
  </p>

  <p id="starts_at_field">
    <%= f.label :starts_at %>
    <%= f.spree_date_picker :starts_at, :prompt => true, :use_month_numbers => true %>
  </p>
  <p id="expires_at_field">
    <%= f.label :expires_at %>
    <%= f.spree_date_picker :expires_at, :prompt => true, :use_month_numbers => true %>
  </p>
</fieldset>

<hr />
<%= render "admin/shared/calculator_fields", :f => f %>

app/views/admin/promotions/_promotion_rule.html.erb
<div class="promotion-rule" id="<%= dom_id promotion_rule %>">
  <span class="delete"><%= link_to_with_icon 'cross', '', admin_promotion_promotion_rule_path(@promotion, promotion_rule), 'data-remote' => true, 'data-method' => 'delete' %></span>
  <% type_name = promotion_rule.class.name.demodulize.underscore %>
  <% param_prefix = "promotion[promotion_rules_attributes][#{promotion_rule.id}]" %>
  <%= hidden_field_tag "#{param_prefix}[id]", promotion_rule.id %>
  <p><%= t "promotion_rule_types.#{type_name}.description" %></p>
  <%= render "admin/promotions/rules/#{type_name}", :promotion_rule => promotion_rule, :param_prefix => param_prefix %>
</div>

app/views/admin/promotions/_tab.html.erb
<%= tab(:promotions) %>

app/views/admin/promotions/edit.html.erb
<h1><%= t("editing_promotion") %></h1>

<%= form_for(@promotion, :url => object_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render "admin/shared/edit_resource_links" %>
<% end %>

<fieldset id="rule_fields">
  <legend><%= t(:rules) %></legend>

  <%= form_for(@promotion, :url => object_url, :html => { :method => :put }) do |f| %>
    <p>
      <% for policy in Promotion::MATCH_POLICIES %>
        <label><%= f.radio_button :match_policy, policy %> <%= t "promotion_form.match_policies.#{policy}" %></label> &nbsp;
      <% end %>
    </p>
    <div id="rules" class="filter_list">
      <% if @promotion.rules.any? %>
        <%= render :partial => 'promotion_rule', :collection => @promotion.rules %>
      <% else %>
        <!-- <p><%= t('no_rules_added') %></p> -->
      <% end %>
    </div>
    <p class="form-buttons">
      <%= button t("update") %>
    </p>
  <% end %>

  <%= form_tag(admin_promotion_promotion_rules_path(@promotion), 'data-remote' => true,
                                                                 :id => 'new_product_rule_form') do  %>
    <% options = options_for_select( PromotionRule.rule_class_names.map {|name| [ t("promotion_rule_types.#{name.demodulize.underscore}.name"), name] } ) %>
    <p>
      <label for="promotion_rule_type"><%= t('add_rule_of_type') %></label>
      <%= select_tag("promotion_rule[type]", options) %>
      <input type="submit" value="<%= t('add') %>" />
    </p>
  <% end %>

</fieldset>



<% content_for :head do %>
  <%= javascript_include_tag 'admin/promotions.js' %>
  <%= stylesheet_link_tag 'admin/promotions.css' %>
<% end %>

app/views/admin/promotions/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_promotion"), new_object_url, :icon => 'add'  %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("promotions") %></h1>

<table class="index">
  <thead>
    <tr>
      <th><%= t("code") %></th>
      <th><%= t("description") %></th>
      <th><%= t("combine") %></th>
      <th><%= t("usage_limit") %></th>
      <th><%= t("expiration") %></th>
      <th><%= t("calculator") %></th>     
      <th width="150"><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% for promotion in @promotions %>
      <tr id="<%= dom_id promotion %>">
        <td><%= promotion.code %></td>
        <td><%= promotion.description %></td>
        <td><%= promotion.combine ? t(:yes) : t(:no) %></td>
        <td><%= promotion.usage_limit %></td>
        <td><%= promotion.expires_at.to_date.to_s(:short_date) if promotion.expires_at %></td>
        <td><%= promotion.calculator.description if promotion.calculator %></td>
        <td>
        	<%= link_to_edit promotion %> &nbsp;
        	<%= link_to_delete promotion %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/promotions/new.html.erb
<h1><%= t("new_promotion") %></h1>
<%= render "shared/error_messages", :target => @promotion %>

<%= form_for(:promotion, :url => collection_url) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render :partial => "admin/shared/new_resource_links" %>
<% end %>

app/views/admin/promotions/rules/_item_total.html.erb
<p class="field">
  <label for="<%= "#{param_prefix}_preferred_amount" %>">
    Item total must be
    <%= select_tag "#{param_prefix}[preferred_operator]", options_for_select(Promotion::Rules::ItemTotal::OPERATORS.map{|o| [t("item_total_rule.operators.#{o}"),o]}, promotion_rule.preferred_operator) %>
    <%= text_field_tag "#{param_prefix}[preferred_amount]", promotion_rule.preferred_amount, :size => 10 %>
  </label>
</p>

app/views/admin/promotions/rules/_product.html.erb
<p class="field products_rule_products_source_field">
  <label><%= radio_button_tag "#{param_prefix}[products_source]", :manual, promotion_rule.product_group.nil? %> <%= t "product_rule.product_source.manual" %></label> &nbsp;
  <label><%= radio_button_tag "#{param_prefix}[products_source]", :group, promotion_rule.product_group.present? %> <%= t "product_rule.product_source.group" %></label>
</p>
<p class="field products_rule_product_group">
  <label><%= t('product_group') %><br />
    <%= select_tag "#{param_prefix}[product_group_id]", options_from_collection_for_select(ProductGroup.all, :id, :name, promotion_rule.product_group_id) %></label>
</p>
<p class="field products_rule_products">
  <label>
    <%= t('product_rule.choose_products') %><br />
    <%= product_picker_field "#{param_prefix}[product_ids_string]", promotion_rule.product_ids_string %>
</p>
<p>
  <label>
    <%= t("product_rule.label", :select => select_tag("#{param_prefix}[preferred_match_policy]", options_for_select(Promotion::Rules::Product::MATCH_POLICIES.map{|s| [t("product_rule.match_#{s}"),s] }, promotion_rule.preferred_match_policy))).html_safe %>
  </label>
</p>

app/views/admin/promotions/rules/_user.html.erb
<p class="field">
  <label>
    <%= t('user_rule.choose_users') %><br />
    <% user_names_hash = promotion_rule.users.inject({}){|memo,item| memo[item.id] = item.email; memo} %>
    <input type="text" name="<%= param_prefix %>[user_ids_string]" value="<%= promotion_rule.user_ids_string %>" class="tokeninput users" data-names='<%= user_names_hash.to_json %>' />
  </label>
</p>

app/views/checkout/_coupon_code_field.html.erb
<% if Promotion.manual.count > 0 %>
<p>
  <%= form.label :coupon_code %><br />
  <%= form.text_field :coupon_code %>
</p>
<% end %>

app/views/products/_promotions.html.erb
<% promotions = @product.possible_promotions %>
<% if promotions.any? %>
<div id="promotions">
  <h3><%= t 'promotions' %></h3>

  <% for promotion in promotions %>
  <div>
    <h4><%= promotion.name %></h4>
    <p><%= promotion.description %></p>
    <% if promotion.products.any? %>
    <ul>
      <% for product in promotion.products %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <% end %>

</div>
<% end %>